title: Kiran Last
position: Doctoral Research Fellow
affiliation: …….. Institute of Technology, ……
email: kkj.nitt.2021@gmail.com
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/Kiran-5
linkedin: https://www.linkedin.com/
avatar: ./assets/img/avatar.png
google_analytics: 
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
